version: "3.8"
services:
    stock_check_nest:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            stock_check_postgres:
                condition: service_healthy
                restart: true

    stock_check_postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
